/****************************************************************************
*   GradeTrackerForm.java                                                   *
*   Jeffery Johnson                                                         *
*   GEEN 165-002                                                            *
*   9/30/15                                                                 *
*                                                                           *
*   This class creates and displays the main gui form for the program       *
*   It also process its action events                                       *
*                                                                           *
****************************************************************************/
package gradetraker;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class GradeTrackerForm extends javax.swing.JFrame {

    private StudentAssignment studentAssignment;  // delcares studentAssignment object        
    JFileChooser fc = new JFileChooser();        
    
    
    public GradeTrackerForm() {
        this.studentAssignment = new StudentAssignment();
        initComponents();       
    } // end default constructor
    
    // constructor if file was passed with command line argument on program startup
    public GradeTrackerForm(String fileName)
    {
        this.studentAssignment = new StudentAssignment();
        initComponents();
        studentAssignment.readGradeFile(fileName);
        JOptionPane.showMessageDialog(null, "File loaded on program startup.");
    } // end constructor with command line argument

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLoadFile = new javax.swing.JButton();
        btnSaveFile = new javax.swing.JButton();
        btnCreateGradeReport = new javax.swing.JButton();
        lblCreateComprehensiveReport = new javax.swing.JLabel();
        lblCreateCategoryReport = new javax.swing.JLabel();
        cmbCategoryReportSelection = new javax.swing.JComboBox();
        btnCreateCategoryReport = new javax.swing.JButton();
        lblLoadSaveDisplay = new javax.swing.JLabel();
        btnAddAssignment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Grade Tracker ");

        btnLoadFile.setText("Load Report");
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });

        btnSaveFile.setText("Save Report");
        btnSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFileActionPerformed(evt);
            }
        });

        btnCreateGradeReport.setText("Create Report");
        btnCreateGradeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGradeReportActionPerformed(evt);
            }
        });

        lblCreateComprehensiveReport.setText("Create comprehensive report");

        lblCreateCategoryReport.setText("Select category to generate report.");

        cmbCategoryReportSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quizzes", "Exams", "Labs", "Programs", "Final Exam" }));

        btnCreateCategoryReport.setText("Create Report");
        btnCreateCategoryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCategoryReportActionPerformed(evt);
            }
        });

        lblLoadSaveDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAddAssignment.setText("Add Assignment");
        btnAddAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSaveFile, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(lblLoadSaveDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCategoryReportSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCreateCategoryReport))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreateComprehensiveReport)
                            .addComponent(btnCreateGradeReport)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreateCategoryReport)
                            .addComponent(btnAddAssignment)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreateComprehensiveReport)
                .addGap(18, 18, 18)
                .addComponent(btnCreateGradeReport)
                .addGap(18, 18, 18)
                .addComponent(lblCreateCategoryReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCategoryReportSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateCategoryReport))
                .addGap(18, 18, 18)
                .addComponent(btnAddAssignment)
                .addGap(18, 18, 18)
                .addComponent(btnLoadFile)
                .addGap(18, 18, 18)
                .addComponent(btnSaveFile)
                .addGap(18, 18, 18)
                .addComponent(lblLoadSaveDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // load file button
    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        
        // this is here so it does not add two files together when another one is loaded.
        studentAssignment = new StudentAssignment();
        
        int loadFile = fc.showOpenDialog(null);
        if (loadFile == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            studentAssignment.readGradeFile(file.getName());
            lblLoadSaveDisplay.setText("File Loaded");
        } // end if
    }//GEN-LAST:event_btnLoadFileActionPerformed

    // save file button
    private void btnSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFileActionPerformed

      
        int saveFile = fc.showOpenDialog( null);
        if (saveFile == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            studentAssignment.saveGradeFile(file.getName());
            lblLoadSaveDisplay.setText("File Saved");
        } //end if
    }//GEN-LAST:event_btnSaveFileActionPerformed

    // create grade report button
    private void btnCreateGradeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGradeReportActionPerformed

        JOptionPane.showMessageDialog(null,studentAssignment.getGradeReport(), "Grade Report",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnCreateGradeReportActionPerformed

    // create category report
    private void btnCreateCategoryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCategoryReportActionPerformed

        int categorySelection = cmbCategoryReportSelection.getSelectedIndex(); // variable to hold category selection
        String tempString = "";                                                // temp variable to be able to display report
        
        // add grade report to tempString variable
        tempString += "Category report for " +Category.toString(categorySelection) +"\n\n";
        studentAssignment.getAssignCategories(categorySelection).setPointsAssigned();
        studentAssignment.getAssignCategories(categorySelection).setPointsEarned();
        tempString += studentAssignment.getAssignCategories(categorySelection).toStringCategoryDisplay(categorySelection);
        
        
        JOptionPane.showMessageDialog(null, tempString, "Category Report",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnCreateCategoryReportActionPerformed

    // create and show AddAssignmentForm to add assignments
    private void btnAddAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssignmentActionPerformed

        // passes in the studentAssignment object to be able to add to it.
        AddAssignmentForm aaf = new AddAssignmentForm(studentAssignment);
        aaf.setVisible(true);
    }//GEN-LAST:event_btnAddAssignmentActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAssignment;
    private javax.swing.JButton btnCreateCategoryReport;
    private javax.swing.JButton btnCreateGradeReport;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnSaveFile;
    private javax.swing.JComboBox cmbCategoryReportSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCreateCategoryReport;
    private javax.swing.JLabel lblCreateComprehensiveReport;
    private javax.swing.JLabel lblLoadSaveDisplay;
    // End of variables declaration//GEN-END:variables


} // end GradeTrackerForm
